### ISSUE TITLE
Chaplain cannot access the side gardens in Lima chapel.

### ISSUE THREAD

**Issue by Wollywoger** [Jolly-66/JollyStationCode#63]
Chaplain cannot access the side gardens in lima chapel.
## Testmerges:
None relevant that I remember

## Reproduction:
![image](https://user-images.githubusercontent.com/88261474/128117438-ca8abe5e-7175-4276-aa56-e9ed3d6276b2.png)
See these little buggers? try and open them as **Chaplain** and find that you are locked out of them for some reason. Yeah sure this is minor, yeah sure some guy might argue that its better this way but chaplain's main gimmick is customization and for the hypothetical anti-nature gimmick having these little pocket gardens are _**absolutely heretical**_ and lacking the ability to customize these slots (without tiding) for other gimmicks is also pretty bothersome

**Comment by Wollywoger** [comment]
didn't notice the thread til after posting this, too late now i suppose

**Comment by sqnztb** [comment]
Known issue, will be fixed with the next big update.

The nature areas used to be filled with butterflies and they'd get out and wander the station, so maint access requirements were added to the windoors to keep them locked in. (And chaplains don't have maint access for whatever reason.) I purged the extra critters a long time ago and just kind of earmarked it "by the way, do this" as something I needed to fix but never implemented it since I was just maintaining the map for myself and not others at that time.

Just smash the windows for now.
